id: I5B92971B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:30:04+00:00'
last_modified: '2022-06-08T02:57:36.390798+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95811
  title: རྒྱུད་བླའི་འགྲེལ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F72B:
      image_group_id: I1PD95838
      title: ''
      total_pages: 388
      order: 1
      base_file: F72B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
