id: P005420
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD95811
  title: རྒྱུད་བླའི་འགྲེལ་པ
  author: ''
  volumes:
    d499a55707a14283a2d560094edb3044:
      image_group_id: I1PD95838
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
