id: P005420
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 11:49:32.625442
source_metadata:
  id: bdr:W1PD95811
  title: རྒྱུད་བླའི་འགྲེལ་པ
  author: ''
  volumes:
    d499a55707a14283a2d560094edb3044:
      image_group_id: I1PD95838
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
